// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

namespace Server.Migrations
{
    [DbContext(typeof(ContextKlasa))]
    partial class ContextKlasaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Server.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<int>("Godina")
                        .HasColumnType("int")
                        .HasColumnName("Godina");

                    b.Property<int?>("KlubId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.Property<int>("Ocena")
                        .HasColumnType("int")
                        .HasColumnName("Ocena");

                    b.Property<string>("Opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Opis");

                    b.Property<string>("Reziser")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Reziser");

                    b.Property<int>("Trajanje")
                        .HasColumnType("int")
                        .HasColumnName("Trajanje");

                    b.Property<string>("Zanr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Zanr");

                    b.HasKey("Id");

                    b.HasIndex("KlubId");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("Server.Models.Glumac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("GodRodjenja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GodRodjenja");

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.Property<string>("MestoRodjenja")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MestoRodjenja");

                    b.Property<string>("Prezime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Prezime");

                    b.HasKey("Id");

                    b.ToTable("Glumci");
                });

            modelBuilder.Entity("Server.Models.Spoj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FilmId")
                        .HasColumnType("int");

                    b.Property<int?>("GlumacId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FilmId");

                    b.HasIndex("GlumacId");

                    b.ToTable("FilmGlumacSpoj");
                });

            modelBuilder.Entity("Server.Models.VideoKlub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.Property<int>("Trenutno")
                        .HasColumnType("int")
                        .HasColumnName("Broj filmova");

                    b.HasKey("Id");

                    b.ToTable("VideoKlub");
                });

            modelBuilder.Entity("Server.Models.Film", b =>
                {
                    b.HasOne("Server.Models.VideoKlub", "Klub")
                        .WithMany("Filmovi")
                        .HasForeignKey("KlubId");

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("Server.Models.Spoj", b =>
                {
                    b.HasOne("Server.Models.Film", "Film")
                        .WithMany("Glumci")
                        .HasForeignKey("FilmId");

                    b.HasOne("Server.Models.Glumac", "Glumac")
                        .WithMany("Film")
                        .HasForeignKey("GlumacId");

                    b.Navigation("Film");

                    b.Navigation("Glumac");
                });

            modelBuilder.Entity("Server.Models.Film", b =>
                {
                    b.Navigation("Glumci");
                });

            modelBuilder.Entity("Server.Models.Glumac", b =>
                {
                    b.Navigation("Film");
                });

            modelBuilder.Entity("Server.Models.VideoKlub", b =>
                {
                    b.Navigation("Filmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
